# Generated by Django 4.1.5 on 2023-01-25 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allergens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('index', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Allergins',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=254)),
                ('EnergyKjoules', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('EnergyKcal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Fat', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Protein', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Carbohydrates', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Salt', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Sugars', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Fibre', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Allergens', models.ManyToManyField(blank=True, related_name='products', to='home.allergens')),
            ],
            options={
                'verbose_name_plural': 'Products',
            },
        ),
    ]
