# Generated by Django 4.1.5 on 2023-02-28 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allergens',
            options={'verbose_name_plural': 'Allergens'},
        ),
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.RemoveField(
            model_name='products',
            name='Allergens',
        ),
        migrations.AddField(
            model_name='products',
            name='Allergens',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
