# Generated by Django 4.1.5 on 2023-03-21 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllergenGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('index', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Allergens',
            },
        ),
        migrations.RemoveField(
            model_name='allergens',
            name='index',
        ),
    ]
