# Generated by Django 4.1.5 on 2023-03-21 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_allergengroup_remove_allergens_index'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Allergens',
        ),
    ]
