# Generated by Django 4.1.5 on 2023-03-21 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_delete_allergens'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
            ],
            options={
                'verbose_name_plural': 'Allergens',
            },
        ),
        migrations.AlterField(
            model_name='allergengroup',
            name='index',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
