# Generated by Django 4.1.5 on 2023-03-21 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_allergens_alter_allergengroup_index'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allergengroup',
            options={'verbose_name_plural': 'Allergen Group'},
        ),
        migrations.RenameField(
            model_name='products',
            old_name='Carbohydrates',
            new_name='carbohydrates',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='EnergyKcal',
            new_name='energy_kcal',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='Allergens',
            new_name='portion_size',
        ),
        migrations.RemoveField(
            model_name='products',
            name='Sugars',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='EnergyKjoules',
            new_name='sugars',
        ),
        migrations.AddField(
            model_name='products',
            name='allergens',
            field=models.ManyToManyField(to='home.allergens'),
        ),
        migrations.AddField(
            model_name='products',
            name='cooked_or_raw',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='home.cookedorraw'),
        ),
        migrations.AddField(
            model_name='products',
            name='deep_frying_index',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='home.source'),
        ),
        migrations.AddField(
            model_name='products',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='home.subcategories'),
        ),
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='home.maincategories'),
        ),
    ]
