# Generated by Django 4.1.5 on 2023-03-23 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_allergengroup_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='Fat',
            new_name='fat',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='Fibre',
            new_name='fibre',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='Protein',
            new_name='protein',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='Salt',
            new_name='salt',
        ),
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='category', to='home.maincategories'),
        ),
        migrations.AlterField(
            model_name='products',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subcategory', to='home.subcategories'),
        ),
    ]
