# Generated by Django 4.1.5 on 2023-03-23 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='category',
        ),
    ]
