# Generated by Django 4.1.5 on 2023-03-23 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_remove_products_cooked_or_raw_remove_products_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='portion_size',
        ),
    ]
