# Generated by Django 4.1.5 on 2023-03-23 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_remove_products_portion_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='energy_kcal',
        ),
    ]
