# Generated by Django 4.1.5 on 2023-03-23 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_remove_products_energy_kcal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='deep_frying_index',
        ),
    ]
