# Generated by Django 4.1.5 on 2023-03-23 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_products_category_products_cooked_or_raw_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='allergens',
            new_name='allergens',
        ),
    ]
