# Generated by Django 4.1.5 on 2023-03-30 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_alter_productallergens_options_products_product_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllergenTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='ProductTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('allergen', models.ManyToManyField(to='home.allergentest')),
            ],
        ),
    ]
