# Generated by Django 4.1.5 on 2023-03-30 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_allergentest_producttest'),
    ]

    operations = [
        migrations.AddField(
            model_name='allergentest',
            name='group',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='allergentest',
            name='index',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
