# Generated by Django 4.1.5 on 2023-03-30 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_allergens_group_allergens_index'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='products',
        #     name='allergens',
        #     field=models.ManyToManyField(to='home.allergens'),
        # ),
        migrations.DeleteModel(
            name='ProductAllergens',
        ),
    ]
