# Generated by Django 4.1.5 on 2023-03-30 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_alter_products_allergens_delete_productallergens'),
    ]

    # operations = [
    #     migrations.RemoveField(
    #         model_name='products',
    #         name='allergens',
    #     ),
    # ]
