# Generated by Django 4.1.5 on 2023-03-31 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_remove_products_allergens'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Products',
        ),
    ]
