# Generated by Django 4.1.5 on 2023-03-31 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_delete_products'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AllergenGroup',
        ),
    ]
