# Generated by Django 4.1.5 on 2023-03-31 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_rename_product_name_products_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='allergens',
            new_name='allergen',
        ),
    ]
