# Generated by Django 4.1.5 on 2023-04-04 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_rename_allergens_products_allergen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allergens',
            name='name',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
