# Generated by Django 4.1.5 on 2023-04-13 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_alter_allergens_index'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allergens',
            old_name='index',
            new_name='eu_index',
        ),
        migrations.AddField(
            model_name='allergens',
            name='us_index',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
